/*
 * InstaDM containment guard — registered as a document-start
 * (AddScriptToExecuteOnDocumentCreatedAsync) script so it runs BEFORE
 * Instagram's own bundles. Instagram is a single-page application: most
 * "navigation" is history.pushState plus DOM swaps that native
 * NavigationStarting never sees. This guard intercepts capture-phase link
 * activation and History API transitions early; the native policy remains
 * the authority and the recovery layer backstops anything that slips by.
 *
 * Policy data is spliced in by the host from the single C# source
 * (PolicyScriptBuilder). There is no hand-written allowlist in this file.
 *
 * PRIVACY: this script never reads message bodies, usernames, input values,
 * cookies, or arbitrary DOM text. The only DOM traversal is walking up from
 * a clicked node to find its enclosing <a href>. Reports to native code (if
 * a bridge exists) carry a coarse surface category — never a URL, query,
 * fragment, or page content.
 *
 * Structure: createGuard(g, policy) builds a guard bound to a global-like
 * object so the Node harness can install it into a fake window. In the
 * WebView the factory is invoked immediately against the real window.
 */
(function () {
  'use strict';

  var POLICY = __INSTADM_POLICY__;

  function createGuard(g, policy) {

    function report(kind, surface) {
      try {
        var webview = g.chrome && g.chrome.webview;
        if (webview && typeof webview.postMessage === 'function') {
          // Schema: fixed keys, enum-like string values, no URLs, no content.
          webview.postMessage({ v: 1, source: 'instadm-guard', kind: kind, surface: surface });
        }
      } catch (e) { /* reporting must never break the page */ }
    }

    // Payload sanity: the payload is generated by the same app binary, so a
    // mismatch is a build defect. Containment then falls to the native
    // policy and recovery layer; a guard misreading data would be worse.
    if (!policy || policy.version !== 1 ||
        !Array.isArray(policy.allowedHosts) || !Array.isArray(policy.dmPrefixes) ||
        !Array.isArray(policy.authPrefixes) || !Array.isArray(policy.optionalPrefixes)) {
      report('guardInactive', 'malformed');
      return null;
    }

    /* -------------- canonicalization (mirrors UrlCanonicalizer.cs) ------ */

    // Returns { host, path } or null. Null always means "treat as hostile".
    function canonicalize(raw, baseHref) {
      var url;
      try {
        url = new URL(raw, baseHref);
      } catch (e) {
        return null;
      }
      if (url.protocol !== 'https:') { return null; }
      if (url.username || url.password) { return null; }
      if (url.port && url.port !== '443') { return null; }

      // URL lowercases the host and converts Unicode labels to punycode, so
      // rejecting xn-- rejects Unicode lookalikes too — same outcome as C#.
      var host = url.hostname.replace(/\.$/, '');
      if (!host || !/^[a-z0-9.-]+$/.test(host)) { return null; }
      var labels = host.split('.');
      for (var i = 0; i < labels.length; i++) {
        if (!labels[i]) { return null; }
        if (labels[i].indexOf('xn--') === 0) { return null; }
      }

      // URL resolves dot segments per RFC 3986 (same as .NET Uri); anything
      // still percent-escaped or containing a backslash is judged hostile.
      var path = url.pathname || '/';
      if (path.indexOf('%') !== -1 || path.indexOf('\\') !== -1) { return null; }
      return { host: host, path: path };
    }

    /* -------------- matching (mirrors PathMatcher.cs) ------------------- */

    function matchesPrefix(path, prefix) {
      return path === prefix || path.indexOf(prefix + '/') === 0;
    }

    function matchesAny(path, prefixes) {
      for (var i = 0; i < prefixes.length; i++) {
        if (matchesPrefix(path, prefixes[i])) { return true; }
      }
      return false;
    }

    /* -------------- judgment -------------------------------------------- */

    // Coarse category for privacy-safe reporting only. Never a URL.
    function surfaceOf(canonical) {
      if (!canonical) { return 'malformed'; }
      if (policy.allowedHosts.indexOf(canonical.host) === -1) { return 'offPlatform'; }
      var p = canonical.path;
      if (p === '/') { return 'feed'; }
      if (matchesPrefix(p, '/explore')) { return 'explore'; }
      if (matchesPrefix(p, '/reel') || matchesPrefix(p, '/reels')) { return 'reels'; }
      if (matchesPrefix(p, '/stories')) { return 'stories'; }
      if (matchesPrefix(p, '/p') || matchesPrefix(p, '/tv')) { return 'post'; }
      if (matchesPrefix(p, '/direct') && !matchesAny(p, policy.dmPrefixes)) { return 'directShell'; }
      return 'other';
    }

    // True when the destination may proceed as a top-level SPA transition.
    function isAllowed(canonical) {
      if (!canonical) { return false; }
      if (policy.allowedHosts.indexOf(canonical.host) === -1) { return false; }
      if (canonical.host === policy.authOnlyHost) { return true; }
      return matchesAny(canonical.path, policy.dmPrefixes) ||
             matchesAny(canonical.path, policy.authPrefixes) ||
             matchesAny(canonical.path, policy.optionalPrefixes);
    }

    // Auth stand-down: while the CURRENT page is a login/challenge/
    // auth_platform surface, interception is suspended entirely.
    // Instagram's auth flows hop through unpredictable intermediate routes;
    // intercepting them trapped login in a loop on macOS
    // (docs/SOURCE_BEHAVIOR.md B5).
    function isStandDown() {
      var current = canonicalize(g.location.href);
      if (!current) { return false; } // hostile current URL: guard stays active
      if (current.host === policy.authOnlyHost) { return true; }
      return matchesAny(current.path, policy.authPrefixes);
    }

    /* -------------- interception ---------------------------------------- */

    function findLinkHref(node) {
      var depth = 0;
      while (node && depth < 64) {
        if (node.tagName && String(node.tagName).toUpperCase() === 'A' &&
            typeof node.getAttribute === 'function') {
          var href = node.getAttribute('href');
          if (href) { return href; }
        }
        node = node.parentNode;
        depth += 1;
      }
      return null;
    }

    function onClickCapture(event) {
      try {
        if (isStandDown()) { return; }
        var href = findLinkHref(event.target);
        if (href === null) { return; }
        if (href.charAt(0) === '#') { return; } // in-page fragment only
        var canonical = canonicalize(href, g.location.href);
        if (isAllowed(canonical)) { return; }
        event.preventDefault();
        if (typeof event.stopImmediatePropagation === 'function') {
          event.stopImmediatePropagation();
        } else if (typeof event.stopPropagation === 'function') {
          event.stopPropagation();
        }
        report('blockedClick', surfaceOf(canonical));
      } catch (e) {
        // Fail closed: judging errors block the activation.
        if (typeof event.preventDefault === 'function') { event.preventDefault(); }
        if (typeof event.stopPropagation === 'function') { event.stopPropagation(); }
        report('blockedClick', 'malformed');
      }
    }

    function wrapHistory(methodName) {
      var original = g.history[methodName];
      if (typeof original !== 'function') { return; }
      g.history[methodName] = function (state, title, url) {
        try {
          // Same-document state updates (url absent) are always fine.
          if (url === undefined || url === null || url === '') {
            return original.apply(g.history, arguments);
          }
          if (isStandDown()) {
            return original.apply(g.history, arguments);
          }
          var canonical = canonicalize(String(url), g.location.href);
          if (isAllowed(canonical)) {
            return original.apply(g.history, arguments);
          }
          report('blockedHistory', surfaceOf(canonical));
          return undefined; // swallow the transition
        } catch (e) {
          report('blockedHistory', 'malformed');
          return undefined; // fail closed
        }
      };
    }

    function install() {
      // Capture phase on window fires before Instagram's own handlers,
      // which attach later (this script runs at document creation) and
      // mostly on document/body in the bubble phase.
      g.addEventListener('click', onClickCapture, true);
      g.addEventListener('auxclick', onClickCapture, true);
      wrapHistory('pushState');
      wrapHistory('replaceState');
      // popstate is deliberately NOT intercepted: back/forward through
      // history the guard already filtered is safe, and the native
      // recovery layer watches committed locations.
    }

    return {
      canonicalize: canonicalize,
      matchesPrefix: matchesPrefix,
      isAllowed: isAllowed,
      surfaceOf: surfaceOf,
      isStandDown: isStandDown,
      install: install
    };
  }

  if (typeof module !== 'undefined' && module.exports) {
    // Node test harness: expose the factory; the harness supplies a fake
    // window and its own policy payload.
    module.exports = { createGuard: createGuard, embeddedPolicy: POLICY };
  } else {
    var guard = createGuard(window, POLICY);
    if (guard) { guard.install(); }
  }
})();
